language: python
python:  
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
before_script:
   - python manage.py migrate
deploy:
  #An issue might be the nested folder structure and name of the app not specified.
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"  
  app: "django-tutorial"
  env: "django-env"
  #bucket_name: "elasticbeanstalk-us-east-1-017801987097"
  on:
    branch: master
script: ./checkFormat.sh
after_script: coveralls
  #haha
  #haha