language: python
python:  
  - "3.7"
# command to install dependencies
install:
  - pip install -r mysite/requirements.txt
  - pip install --upgrade django==2.2
#before_script:
   #- python manage.py migrate
deploy:
  #An issue might be the nested folder structure and name of the app not specified.
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: $SECRETACCESSKEY
  region: "us-west-2"  
  app: "django-tutorial"
  env: "django-env"
  bucket_name: "elasticbeanstalk-us-west-2-120100994814"
  on:
    branch: main
script: source checkFormat.sh
after_script: coveralls
  #haha
  #haha